export const ECHARTS_COUNTRY_MAP: Record<string, string> = {
  AD: 'Andorra',
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AG: 'Antigua and Barbuda',
  AI: 'Anguilla',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AQ: 'Antarctica',
  AR: 'Argentina',
  AS: 'American Samoa',
  AT: 'Austria',
  AU: 'Australia',
  AW: 'Aruba',
  AX: 'Åland Islands',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BL: 'Saint Barthélemy',
  BM: 'Bermuda',
  BN: 'Brunei Darussalam',
  BO: 'Bolivia',
  BQ: 'Bonaire, Sint Eustatius and Saba',
  BR: 'Brazil',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BV: 'Bouvet Island',
  BW: 'Botswana',
  BY: 'Belarus',
  BZ: 'Belize',
  CA: 'Canada',
  CC: 'Cocos (Keeling) Islands',
  CD: 'Congo, Democratic Republic of the',
  CF: 'Central African Republic',
  CG: 'Congo',
  CH: 'Switzerland',
  CI: "Côte d'Ivoire",
  CK: 'Cook Islands',
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cabo Verde',
  CW: 'Curaçao',
  CX: 'Christmas Island',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DE: 'Germany',
  DJ: 'Djibouti',
  DK: 'Denmark',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  EH: 'Western Sahara',
  ER: 'Eritrea',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FK: 'Falkland Islands (Malvinas)',
  FM: 'Micronesia, Federated States of',
  FO: 'Faroe Islands',
  FR: 'France',
  GA: 'Gabon',
  GB: 'United Kingdom',
  GD: 'Grenada',
  GE: 'Georgia',
  GF: 'French Guiana',
  GG: 'Guernsey',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GL: 'Greenland',
  GM: 'Gambia',
  GN: 'Guinea',
  GP: 'Guadeloupe',
  GQ: 'Equatorial Guinea',
  GR: 'Greece',
  GS: 'South Georgia and the South Sandwich Islands',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HK: 'Hong Kong',
  HM: 'Heard Island and McDonald Islands',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IM: 'Isle of Man',
  IN: 'India',
  IO: 'British Indian Ocean Territory',
  IQ: 'Iraq',
  IR: 'Iran, Islamic Republic of',
  IS: 'Iceland',
  IT: 'Italy',
  JE: 'Jersey',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KI: 'Kiribati',
  KM: 'Comoros',
  KN: 'Saint Kitts and Nevis',
  KP: "Korea, Democratic People's Republic of",
  KR: 'South Korea',
  KW: 'Kuwait',
  KY: 'Cayman Islands',
  KZ: 'Kazakhstan',
  LA: "Lao People's Democratic Republic",
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LS: 'Lesotho',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  LY: 'Libya',
  MA: 'Morocco',
  MC: 'Monaco',
  MD: 'Moldova, Republic of',
  ME: 'Montenegro',
  MF: 'Saint Martin (French part)',
  MG: 'Madagascar',
  MH: 'Marshall Islands',
  MK: 'North Macedonia',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MO: 'Macao',
  MP: 'Northern Mariana Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MW: 'Malawi',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NC: 'New Caledonia',
  NE: 'Niger',
  NF: 'Norfolk Island',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PM: 'Saint Pierre and Miquelon',
  PN: 'Pitcairn',
  PR: 'Puerto Rico',
  PS: 'Palestine, State of',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Qatar',
  RE: 'Réunion',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SB: 'Solomon Islands',
  SC: 'Seychelles',
  SD: 'Sudan',
  SE: 'Sweden',
  SG: 'Singapore',
  SH: 'Saint Helena, Ascension and Tristan da Cunha',
  SI: 'Slovenia',
  SJ: 'Svalbard and Jan Mayen',
  SK: 'Slovakia',
  SL: 'Sierra Leone',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Suriname',
  SS: 'South Sudan',
  ST: 'Sao Tome and Principe',
  SV: 'El Salvador',
  SX: 'Sint Maarten (Dutch part)',
  SY: 'Syrian Arab Republic',
  SZ: 'Eswatini',
  TC: 'Turks and Caicos Islands',
  TD: 'Chad',
  TF: 'French Southern Territories',
  TG: 'Togo',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TK: 'Tokelau',
  TL: 'Timor-Leste',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TO: 'Tonga',
  TR: 'Turkey',
  TT: 'Trinidad and Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan, Province of China',
  TZ: 'Tanzania',
  UA: 'Ukraine',
  UG: 'Uganda',
  UM: 'United States Minor Outlying Islands',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VA: 'Holy See',
  VC: 'Saint Vincent and the Grenadines',
  VE: 'Venezuela',
  VG: 'Virgin Islands (British)',
  VI: 'Virgin Islands (U.S.)',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WF: 'Wallis and Futuna',
  WS: 'Samoa',
  YE: 'Yemen',
  YT: 'Mayotte',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
}

const REVERSE_COUNTRY_MAP = Object.fromEntries(Object.entries(ECHARTS_COUNTRY_MAP).map(([k, v]) => [v.toUpperCase(), k]))

export function normalizeCountryCode(country: string): string {
  const code = country.trim().toUpperCase()

  if (ECHARTS_COUNTRY_MAP[code]) {
    return code
  }

  if (REVERSE_COUNTRY_MAP[code]) {
    return REVERSE_COUNTRY_MAP[code]
  }

  const variations: Record<string, string> = {
    'UNITED STATES': 'US',
    'UNITED STATES OF AMERICA': 'US',
    USA: 'US',
    EUA: 'US',
    'ESTADOS UNIDOS': 'US',
    CANADA: 'CA',
    CANADÁ: 'CA',
    MEXICO: 'MX',
    MÉXICO: 'MX',
    BRASIL: 'BR',
    BRAZIL: 'BR',
    ARGENTINA: 'AR',
    CHILE: 'CL',
    COLOMBIA: 'CO',
    COLÔMBIA: 'CO',
    PERU: 'PE',
    PERÚ: 'PE',
    VENEZUELA: 'VE',
    URUGUAY: 'UY',
    URUGUAI: 'UY',
    'UNITED KINGDOM': 'GB',
    UK: 'GB',
    'GREAT BRITAIN': 'GB',
    ENGLAND: 'GB',
    'REINO UNIDO': 'GB',
    INGLATERRA: 'GB',
    PORTUGAL: 'PT',
    SPAIN: 'ES',
    ESPAÑA: 'ES',
    ESPANHA: 'ES',
    FRANCE: 'FR',
    FRANÇA: 'FR',
    GERMANY: 'DE',
    ALEMANHA: 'DE',
    DEUTSCHLAND: 'DE',
    ITALY: 'IT',
    ITÁLIA: 'IT',
    ITALIA: 'IT',
    NETHERLANDS: 'NL',
    HOLANDA: 'NL',
    'THE NETHERLANDS': 'NL',
    'PAÍSES BAIXOS': 'NL',
    SWITZERLAND: 'CH',
    SUÍÇA: 'CH',
    SUIÇA: 'CH',
    SWEDEN: 'SE',
    SUÉCIA: 'SE',
    SUECIA: 'SE',
    NORWAY: 'NO',
    NORUEGA: 'NO',
    DENMARK: 'DK',
    DINAMARCA: 'DK',
    FINLAND: 'FI',
    FINLÂNDIA: 'FI',
    FINLANDIA: 'FI',
    IRELAND: 'IE',
    IRLANDA: 'IE',
    BELGIUM: 'BE',
    BÉLGICA: 'BE',
    BELGICA: 'BE',
    AUSTRIA: 'AT',
    ÁUSTRIA: 'AT',
    GREECE: 'GR',
    GRÉCIA: 'GR',
    GRECIA: 'GR',
    POLAND: 'PL',
    POLÔNIA: 'PL',
    POLONIA: 'PL',
    RUSSIA: 'RU',
    RÚSSIA: 'RU',
    UKRAINE: 'UA',
    UCRÂNIA: 'UA',
    UCRANIA: 'UA',
    JAPAN: 'JP',
    JAPÃO: 'JP',
    JAPAO: 'JP',
    CHINA: 'CN',
    INDIA: 'IN',
    ÍNDIA: 'IN',
    'SOUTH KOREA': 'KR',
    KOREA: 'KR',
    'COREIA DO SUL': 'KR',
    'CORÉIA DO SUL': 'KR',
    AUSTRALIA: 'AU',
    AUSTRÁLIA: 'AU',
    'NEW ZEALAND': 'NZ',
    'NOVA ZELÂNDIA': 'NZ',
    'NOVA ZELANDIA': 'NZ',
    INDONESIA: 'ID',
    INDONÉSIA: 'ID',
    'SOUTH AFRICA': 'ZA',
    'ÁFRICA DO SUL': 'ZA',
    'AFRICA DO SUL': 'ZA',
    EGYPT: 'EG',
    EGITO: 'EG',
    ISRAEL: 'IL',
    TURKEY: 'TR',
    TURQUIA: 'TR',
    'SAUDI ARABIA': 'SA',
    'ARÁBIA SAUDITA': 'SA',
    'ARABIA SAUDITA': 'SA',
    'UNITED ARAB EMIRATES': 'AE',
    UAE: 'AE',
    'EMIRADOS ÁRABES UNIDOS': 'AE',
    'EMIRADOS ARABES': 'AE',
  }

  return variations[code] || code
}
